In [ ]:
pip install opendatasets

Collecting opendatasets
  Downloading opendatasets-0.1.22-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from opendatasets) (4.67.1)
Requirement already satisfied: kaggle in /usr/local/lib/python3.11/dist-packages (from opendatasets) (1.7.4.2)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from opendatasets) (8.1.8)
Requirement already satisfied: bleach in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (2025.1.31)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (3.4.1)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (3.10)
Requirement already satisfied: protobuf in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (5.29.4)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (2.8.2)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (2.32.3)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (1.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (2.3.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (0.5.1)
Downloading opendatasets-0.1.22-py3-none-any.whl (15 kB)
Installing collected packages: opendatasets
Successfully installed opendatasets-0.1.22

In [ ]:
import opendatasets as od
od.download("https://www.kaggle.com/datasets/berkayalan/ecommerce-sales-dataset")

Skipping, found downloaded files in "./ecommerce-sales-dataset" (use force=True to force download)

In [ ]:
import pandas as pd
data=pd.read_csv("/content/ecommerce-sales-dataset/basket_details.csv")

In [ ]:
data.head()

   customer_id  product_id basket_date  basket_count
0     42366585    41475073  2019-06-19             2
1     35956841    43279538  2019-06-19             2
2     26139578    31715598  2019-06-19             3
3      3262253    47880260  2019-06-19             2
4     20056678    44747002  2019-06-19             2

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_id   15000 non-null  int64
 1   product_id    15000 non-null  int64
 2   basket_date   15000 non-null  object
 3   basket_count  15000 non-null  int64
dtypes: int64(3), object(1)
memory usage: 468.9+ KB

In [ ]:
data.describe()

        customer_id    product_id  basket_count
count  1.500000e+04  1.500000e+04  15000.000000
mean   1.808567e+07  3.269771e+07      2.153733
std    1.233000e+07  1.629455e+07      0.517929
min    4.784000e+03  4.939000e+04      2.000000
25%    8.659327e+06  3.137412e+07      2.000000
50%    1.520775e+07  3.694759e+07      2.000000
75%    2.663904e+07  4.502408e+07      2.000000
max    4.460824e+07  5.579097e+07     10.000000

In [ ]:
data.isnull().sum()

NameError: name 'data' is not defined

In [ ]:
print("Column Names:", data.columns.tolist())

Column Names: ['customer_id', 'product_id', 'basket_date', 'basket_count']

In [ ]:
for col in data.select_dtypes(include='object').columns:
    print(f"\nUnique values in {col}:")
    print(data[col].unique()[:10])

Unique values in basket_date:
['2019-06-19' '2019-06-18' '2019-06-17' '2019-06-16' '2019-06-15'
 '2019-06-14' '2019-06-13' '2019-06-12' '2019-06-11' '2019-06-10']

In [ ]:
import pandas as pd
data=pd.read_csv("/content/ecommerce-sales-dataset/customer_details.csv")

In [ ]:
data.head()

   customer_id   sex  customer_age  tenure
0      9798859  Male          44.0      93
1     11413563  Male          36.0      65
2       818195  Male          35.0     129
3     12049009  Male          33.0      58
4     10083045  Male          42.0      88

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_id   20000 non-null  int64
 1   sex           20000 non-null  object
 2   customer_age  20000 non-null  float64
 3   tenure        20000 non-null  int64
dtypes: float64(1), int64(2), object(1)
memory usage: 625.1+ KB

In [ ]:
data.describe()

        customer_id  customer_age        tenure
count  2.000000e+04  20000.000000  20000.000000
mean   1.760040e+07    262.222550     44.396800
std    8.679505e+06    604.321589     31.998376
min    2.093000e+03    -34.000000      4.000000
25%    1.188115e+07     29.000000     21.000000
50%    1.560912e+07     38.000000     35.000000
75%    2.228484e+07    123.000000     60.000000
max    4.462566e+07   2022.000000    133.000000

In [ ]:
print("Column Names:", data.columns.tolist())

Column Names: ['customer_id', 'sex', 'customer_age', 'tenure']

In [ ]:
data.isnull().sum()

customer_id     0
sex             0
customer_age    0
tenure          0
dtype: int64

In [ ]:
for col in data.select_dtypes(include='object').columns:
    print(f"\nUnique values in {col}:")
    print(data[col].unique()[:10])

Unique values in sex:
['Male' 'Female' 'kvkktalepsilindi' 'UNKNOWN']